In [1]:
import pandas as pd
import numpy as np

In [2]:
# 1、读取数据
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
column_name = ['Sample code number', 'Clump Thickness', 'Uniformity of Cell Size', 'Uniformity of Cell Shape',
                   'Marginal Adhesion', 'Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin',
                   'Normal Nucleoli', 'Mitoses', 'Class']
data = pd.read_csv(path,names=column_name)

In [3]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [4]:
# 2、缺失值处理
# 2.1、替换？->nan
data = data.replace(to_replace="?",value=np.nan)
# 2.2、删除确实样本
data.dropna(inplace=True)

In [5]:
data.isnull().any() # 不存在缺失值

Sample code number             False
Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
Class                          False
dtype: bool

In [6]:
# 3、划分数据集
from sklearn.model_selection import train_test_split

In [7]:
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

  Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0           1                3                1        1      2  
1          10                3                2        1      2  
2           2                3                1        1      2  
3           4                3                7        1      2  
4           1                3                1        1      2

In [8]:
# 筛选特征和目标值
x=data.iloc[:,1:-1]
y=data["Class"]

In [9]:
x.head()

Clump Thickness  Uniformity of Cell Size  Uniformity of Cell Shape  \
0                5                        1                         1   
1                5                        4                         4   
2                3                        1                         1   
3                6                        8                         8   
4                4                        1                         1   

   Marginal Adhesion  Single Epithelial Cell Size Bare Nuclei  \
0                  1                            2           1   
1                  5                            7          10   
2                  1                            2           2   
3                  1                            3           4   
4                  3                            2           1   

   Bland Chromatin  Normal Nucleoli  Mitoses  
0                3                1        1  
1                3                2        1  
2                3                1        1  
3                3                7        1  
4                3                1        1

In [10]:
y.head()

0    2
1    2
2    2
3    2
4    2
Name: Class, dtype: int64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y)

In [12]:
x_train.isnull().any()

Clump Thickness                False
Uniformity of Cell Size        False
Uniformity of Cell Shape       False
Marginal Adhesion              False
Single Epithelial Cell Size    False
Bare Nuclei                    False
Bland Chromatin                False
Normal Nucleoli                False
Mitoses                        False
dtype: bool

In [13]:
# 4、特征工程：标准化
from sklearn.preprocessing import StandardScaler

In [14]:
transfer = StandardScaler()
x_train = transfer.fit_transform(x_train)
x_test = transfer.transform(x_test)

In [15]:
x_train

array([[ 1.54685118,  2.13140671,  2.18989977, ...,  2.59700596,
         2.24793703, -0.3679486 ],
       [-0.20378499, -0.71788894, -0.76848725, ..., -1.00642778,
        -0.63102179, -0.3679486 ],
       [-1.2541667 , -0.71788894, -0.76848725, ..., -0.20566473,
        -0.63102179, -0.3679486 ],
       ...,
       [ 1.89697842,  0.23187627,  0.54635142, ...,  1.39586138,
         0.00874684, -0.3679486 ],
       [-0.55391223, -0.71788894, -0.76848725, ...,  0.59509832,
         1.6081684 , -0.3679486 ],
       [-0.55391223, -0.71788894, -0.76848725, ..., -0.60604626,
        -0.63102179, -0.3679486 ]])

In [16]:
from sklearn.linear_model import LogisticRegression

In [17]:
# 5、预估器流程
estimator = LogisticRegression()
estimator.fit(x_train,y_train)

LogisticRegression()

In [18]:
# 回归系数和偏置
estimator.coef_

array([[1.16462865, 0.05581641, 0.93093303, 0.98740337, 0.44106797,
        1.46261332, 0.77215962, 0.59891719, 0.63219509]])

In [19]:
estimator.intercept_

array([-0.87614373])

In [21]:
# 6、模型评估
 # 方法1:直接比对真实值和预测值
y_predict = estimator.predict(x_test)
print("y_predict:\n", y_predict)
print("直接比对真实值和预测值:\n", y_test == y_predict)

# 方法2:计算准确率
score = estimator.score(x_test,y_test)
print("准确率为：\n",score)

y_predict:
 [4 2 2 2 2 4 2 2 4 2 2 4 2 2 2 4 2 2 2 4 2 4 4 4 2 4 4 2 2 2 2 2 2 2 2 4 2
 2 2 4 2 4 4 2 2 2 2 4 2 4 2 2 4 4 2 4 4 4 4 2 2 2 2 2 2 2 2 4 2 2 2 2 2 4
 2 2 2 2 2 4 2 4 2 2 4 2 2 4 2 2 4 2 2 2 2 4 4 2 2 2 2 2 4 4 2 2 2 2 2 2 2
 4 2 2 2 4 2 4 2 2 2 2 2 2 4 4 2 2 4 4 2 2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 2 4
 2 4 2 2 2 2 4 2 4 4 2 2 2 2 2 2 2 2 2 4 2 4 4]
直接比对真实值和预测值:
 353     True
204     True
526     True
16      True
452     True
       ...  
133     True
333     True
537     True
352    False
610     True
Name: Class, Length: 171, dtype: bool
准确率为：
 0.9532163742690059


In [22]:
# 查看精确率，召回率已经F1-score
from sklearn.metrics import classification_report

In [23]:
report = classification_report(y_test,y_predict,labels=[2,4],target_names=["良性","恶性"])

In [24]:
print(report)

              precision    recall  f1-score   support

          良性       0.97      0.96      0.97       119
          恶性       0.91      0.94      0.92        52

    accuracy                           0.95       171
   macro avg       0.94      0.95      0.95       171
weighted avg       0.95      0.95      0.95       171



In [25]:
# y_true:每个样本的真实类别，必须为0(反例),1(正例)标记
# 将y_test转换为0，1
y_true = np.where(y_test>3,1,0)

In [26]:
y_true

array([1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [27]:
from sklearn.metrics import roc_auc_score

In [28]:
roc_auc_score(y_true,y_predict)

0.9501454427925017